# Generated by Django 5.1 on 2024-10-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_list_image_url_list_winner_list_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='oferta_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
