# Generated by Django 5.1 on 2024-10-02 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='oferta_inicial',
            new_name='starting_bid',
        ),
    ]
