# Generated by Django 5.1 on 2024-10-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_commentary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='comment',
            new_name='content',
        ),
        migrations.AddField(
            model_name='commentary',
            name='headline',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
