# Generated by Django 5.1 on 2024-10-03 03:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_comment_commentary_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
